# Generated by Django 3.2.6 on 2021-08-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keeps_challenges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='nome',
            new_name='name',
        ),
    ]
