# Generated by Django 3.2.6 on 2021-08-07 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keeps_challenges', '0003_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aluno',
            new_name='Student',
        ),
    ]
