# Generated by Django 3.2.6 on 2021-08-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeps_challenges', '0004_rename_aluno_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='rg',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='student',
            name='nickname',
            field=models.CharField(default='', max_length=9),
            preserve_default=False,
        ),
    ]
