# Generated by Django 3.2.6 on 2021-08-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeps_challenges', '0005_auto_20210807_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
