# Generated by Django 3.2.6 on 2021-08-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keeps_challenges', '0006_course_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
    ]
