# Generated by Django 3.2.6 on 2021-08-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeps_challenges', '0007_remove_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
