# Generated by Django 3.2.6 on 2021-08-07 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeps_challenges', '0013_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='student',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
