# Generated by Django 3.2.6 on 2021-08-07 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keeps_challenges', '0016_auto_20210807_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='keeps_challenges.course'),
        ),
    ]
