# Generated by Django 3.2.6 on 2021-08-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keeps_challenges', '0019_auto_20210808_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='status',
            new_name='name',
        ),
    ]
