# Generated by Django 3.2.6 on 2021-08-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keeps_challenges', '0020_rename_status_status_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='name',
            new_name='status',
        ),
    ]
